// User
const SET_TOKEN = 'SET_TOKEN'
const SET_USER = 'SET_USER'
const CLEAR_USER = 'CLEAR_USER'
const USER_ERRORS = 'USER_ERRORS'
// const CLEAR_ERRORS = 'CLEAR_ERRORS'

// Store
const SET_STORES = 'SET_STORES'
const LOADING_STORES = 'LOADING_STORES'
const ADD_STORE = 'ADD_STORE'
const ADD_ITEM_TO_STORE = 'ADD_ITEM_TO_STORE'
const STORE_ERRORS = 'STORE_ERRORS'
const SET_STORE_ID = 'SET_STORE_ID'

// Item
const ADD_ITEM = 'ADD_ITEM'
const ITEM_ERRORS = 'ITEM_ERRORS'

// Errors
const SET_ERRORS = 'SET_ERRORS'
const CLEAR_ERRORS = 'CLEAR_ERRORS'

export {
    // User
    SET_TOKEN,
    SET_USER,
    CLEAR_USER,
    USER_ERRORS,
    // CLEAR_ERRORS,

    // Store
    SET_STORES,
    LOADING_STORES,
    ADD_STORE,
    ADD_ITEM_TO_STORE,
    STORE_ERRORS,
    SET_STORE_ID,

    // Item
    ADD_ITEM,
    ITEM_ERRORS,

    // Errors
    SET_ERRORS,
    CLEAR_ERRORS
}