// User
const SET_TOKEN = 'SET_TOKEN'
const SET_USER = 'SET_USER'
const CLEAR_USER = 'CLEAR_USER'
const USER_ERRORS = 'USER_ERRORS'

// Store
const SET_STORES = 'SET_STORES'
const LOADING_STORES = 'LOADING_STORES'
const ADD_STORE = 'ADD_STORE'
const STORE_ERRORS = 'STORE_ERRORS'
const SET_STORE_ID = 'SET_STORE_ID'
const UPDATE_STORE = 'UPDATE_STORE'

// Item
const SET_ITEMS = 'SET_ITEMS'
const LOADING_ITEMS = 'LOADING_ITEMS'
const ADD_ITEM = 'ADD_ITEM'
const ITEM_ERRORS = 'ITEM_ERRORS'

// Errors
const SET_ERRORS = 'SET_ERRORS'
const CLEAR_ERRORS = 'CLEAR_ERRORS'

// Is Open?
const NEW_STORE_OPEN = 'NEW_STORE_OPEN'
const NEW_STORE_CLOSE = 'NEW_STORE_CLOSE'

export {
    // User
    SET_TOKEN,
    SET_USER,
    CLEAR_USER,
    USER_ERRORS,

    // Store
    SET_STORES,
    LOADING_STORES,
    ADD_STORE,
    STORE_ERRORS,
    SET_STORE_ID,
    UPDATE_STORE,

    // Item
    SET_ITEMS,
    LOADING_ITEMS,
    ADD_ITEM,
    ITEM_ERRORS,

    // Errors
    SET_ERRORS,
    CLEAR_ERRORS,

    // Is Open?
    NEW_STORE_OPEN,
    NEW_STORE_CLOSE,
}