const SET_TOKEN = 'SET_TOKEN'
const SET_USER = 'SET_USER'
const CLEAR_USER = 'CLEAR_USER'
const USER_ERRORS = 'USER_ERRORS'
const CLEAR_ERRORS = 'CLEAR_ERRORS'

const SET_STORES = 'SET_STORES'
const LOADING_STORES = 'LOADING_STORES'

export {
    SET_TOKEN,
    SET_USER,
    CLEAR_USER,
    USER_ERRORS,
    CLEAR_ERRORS,

    SET_STORES,
    LOADING_STORES
}